// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

// Protobuf Java Version: 3.25.1
package com.sparrow.switcher.common.grpc.auto;

public final class TestProto {
  private TestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 错误码 0:成功; 其他：参考《错误码统计》
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <pre>
     * 错误消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * 错误消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code BaseResponse}
   */
  public static final class BaseResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BaseResponse)
      BaseResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseResponse.newBuilder() to construct.
    private BaseResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseResponse() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BaseResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_BaseResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_BaseResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.class, com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_ = 0;
    /**
     * <pre>
     * 错误码 0:成功; 其他：参考《错误码统计》
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <pre>
     * 错误消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 错误消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse)) {
        return super.equals(obj);
      }
      com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse other = (com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseResponse)
        com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_BaseResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_BaseResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.class, com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.Builder.class);
      }

      // Construct using com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        code_ = 0;
        message_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_BaseResponse_descriptor;
      }

      @java.lang.Override
      public com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse getDefaultInstanceForType() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse build() {
        com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse buildPartial() {
        com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse result = new com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.message_ = message_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse) {
          return mergeFrom((com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse other) {
        if (other == com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                code_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <pre>
       * 错误码 0:成功; 其他：参考《错误码统计》
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * 错误码 0:成功; 其他：参考《错误码统计》
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {

        code_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误码 0:成功; 其他：参考《错误码统计》
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * 错误消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 错误消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 错误消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BaseResponse)
    }

    // @@protoc_insertion_point(class_scope:BaseResponse)
    private static final com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse();
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseResponse>
        PARSER = new com.google.protobuf.AbstractParser<BaseResponse>() {
      @java.lang.Override
      public BaseResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BaseResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VersionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Version)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 软件版本号
     * </pre>
     *
     * <code>string software_version = 1;</code>
     * @return The softwareVersion.
     */
    java.lang.String getSoftwareVersion();
    /**
     * <pre>
     * 软件版本号
     * </pre>
     *
     * <code>string software_version = 1;</code>
     * @return The bytes for softwareVersion.
     */
    com.google.protobuf.ByteString
        getSoftwareVersionBytes();

    /**
     * <pre>
     * 上次编译时间
     * </pre>
     *
     * <code>int64 last_compile_time = 2;</code>
     * @return The lastCompileTime.
     */
    long getLastCompileTime();
  }
  /**
   * <pre>
   *
   ** 版本信息
   * </pre>
   *
   * Protobuf type {@code Version}
   */
  public static final class Version extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Version)
      VersionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Version.newBuilder() to construct.
    private Version(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Version() {
      softwareVersion_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Version();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_Version_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_Version_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrow.switcher.common.grpc.auto.TestProto.Version.class, com.sparrow.switcher.common.grpc.auto.TestProto.Version.Builder.class);
    }

    public static final int SOFTWARE_VERSION_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object softwareVersion_ = "";
    /**
     * <pre>
     * 软件版本号
     * </pre>
     *
     * <code>string software_version = 1;</code>
     * @return The softwareVersion.
     */
    @java.lang.Override
    public java.lang.String getSoftwareVersion() {
      java.lang.Object ref = softwareVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        softwareVersion_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 软件版本号
     * </pre>
     *
     * <code>string software_version = 1;</code>
     * @return The bytes for softwareVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSoftwareVersionBytes() {
      java.lang.Object ref = softwareVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        softwareVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_COMPILE_TIME_FIELD_NUMBER = 2;
    private long lastCompileTime_ = 0L;
    /**
     * <pre>
     * 上次编译时间
     * </pre>
     *
     * <code>int64 last_compile_time = 2;</code>
     * @return The lastCompileTime.
     */
    @java.lang.Override
    public long getLastCompileTime() {
      return lastCompileTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(softwareVersion_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, softwareVersion_);
      }
      if (lastCompileTime_ != 0L) {
        output.writeInt64(2, lastCompileTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(softwareVersion_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, softwareVersion_);
      }
      if (lastCompileTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, lastCompileTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sparrow.switcher.common.grpc.auto.TestProto.Version)) {
        return super.equals(obj);
      }
      com.sparrow.switcher.common.grpc.auto.TestProto.Version other = (com.sparrow.switcher.common.grpc.auto.TestProto.Version) obj;

      if (!getSoftwareVersion()
          .equals(other.getSoftwareVersion())) return false;
      if (getLastCompileTime()
          != other.getLastCompileTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOFTWARE_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getSoftwareVersion().hashCode();
      hash = (37 * hash) + LAST_COMPILE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastCompileTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.Version parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.Version parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.Version parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.Version parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.Version parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.Version parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.Version parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.Version parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.Version parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.Version parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.Version parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.Version parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sparrow.switcher.common.grpc.auto.TestProto.Version prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *
     ** 版本信息
     * </pre>
     *
     * Protobuf type {@code Version}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Version)
        com.sparrow.switcher.common.grpc.auto.TestProto.VersionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_Version_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_Version_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sparrow.switcher.common.grpc.auto.TestProto.Version.class, com.sparrow.switcher.common.grpc.auto.TestProto.Version.Builder.class);
      }

      // Construct using com.sparrow.switcher.common.grpc.auto.TestProto.Version.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        softwareVersion_ = "";
        lastCompileTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_Version_descriptor;
      }

      @java.lang.Override
      public com.sparrow.switcher.common.grpc.auto.TestProto.Version getDefaultInstanceForType() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.Version.getDefaultInstance();
      }

      @java.lang.Override
      public com.sparrow.switcher.common.grpc.auto.TestProto.Version build() {
        com.sparrow.switcher.common.grpc.auto.TestProto.Version result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sparrow.switcher.common.grpc.auto.TestProto.Version buildPartial() {
        com.sparrow.switcher.common.grpc.auto.TestProto.Version result = new com.sparrow.switcher.common.grpc.auto.TestProto.Version(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.sparrow.switcher.common.grpc.auto.TestProto.Version result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.softwareVersion_ = softwareVersion_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.lastCompileTime_ = lastCompileTime_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sparrow.switcher.common.grpc.auto.TestProto.Version) {
          return mergeFrom((com.sparrow.switcher.common.grpc.auto.TestProto.Version)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sparrow.switcher.common.grpc.auto.TestProto.Version other) {
        if (other == com.sparrow.switcher.common.grpc.auto.TestProto.Version.getDefaultInstance()) return this;
        if (!other.getSoftwareVersion().isEmpty()) {
          softwareVersion_ = other.softwareVersion_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getLastCompileTime() != 0L) {
          setLastCompileTime(other.getLastCompileTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                softwareVersion_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                lastCompileTime_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object softwareVersion_ = "";
      /**
       * <pre>
       * 软件版本号
       * </pre>
       *
       * <code>string software_version = 1;</code>
       * @return The softwareVersion.
       */
      public java.lang.String getSoftwareVersion() {
        java.lang.Object ref = softwareVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          softwareVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 软件版本号
       * </pre>
       *
       * <code>string software_version = 1;</code>
       * @return The bytes for softwareVersion.
       */
      public com.google.protobuf.ByteString
          getSoftwareVersionBytes() {
        java.lang.Object ref = softwareVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          softwareVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 软件版本号
       * </pre>
       *
       * <code>string software_version = 1;</code>
       * @param value The softwareVersion to set.
       * @return This builder for chaining.
       */
      public Builder setSoftwareVersion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        softwareVersion_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 软件版本号
       * </pre>
       *
       * <code>string software_version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSoftwareVersion() {
        softwareVersion_ = getDefaultInstance().getSoftwareVersion();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 软件版本号
       * </pre>
       *
       * <code>string software_version = 1;</code>
       * @param value The bytes for softwareVersion to set.
       * @return This builder for chaining.
       */
      public Builder setSoftwareVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        softwareVersion_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long lastCompileTime_ ;
      /**
       * <pre>
       * 上次编译时间
       * </pre>
       *
       * <code>int64 last_compile_time = 2;</code>
       * @return The lastCompileTime.
       */
      @java.lang.Override
      public long getLastCompileTime() {
        return lastCompileTime_;
      }
      /**
       * <pre>
       * 上次编译时间
       * </pre>
       *
       * <code>int64 last_compile_time = 2;</code>
       * @param value The lastCompileTime to set.
       * @return This builder for chaining.
       */
      public Builder setLastCompileTime(long value) {

        lastCompileTime_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 上次编译时间
       * </pre>
       *
       * <code>int64 last_compile_time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastCompileTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastCompileTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Version)
    }

    // @@protoc_insertion_point(class_scope:Version)
    private static final com.sparrow.switcher.common.grpc.auto.TestProto.Version DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sparrow.switcher.common.grpc.auto.TestProto.Version();
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.Version getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Version>
        PARSER = new com.google.protobuf.AbstractParser<Version>() {
      @java.lang.Override
      public Version parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Version> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Version> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sparrow.switcher.common.grpc.auto.TestProto.Version getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetVersionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetVersionRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code GetVersionRequest}
   */
  public static final class GetVersionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetVersionRequest)
      GetVersionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetVersionRequest.newBuilder() to construct.
    private GetVersionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetVersionRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetVersionRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_GetVersionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_GetVersionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest.class, com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest)) {
        return super.equals(obj);
      }
      com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest other = (com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetVersionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetVersionRequest)
        com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_GetVersionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_GetVersionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest.class, com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest.Builder.class);
      }

      // Construct using com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_GetVersionRequest_descriptor;
      }

      @java.lang.Override
      public com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest getDefaultInstanceForType() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest build() {
        com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest buildPartial() {
        com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest result = new com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest) {
          return mergeFrom((com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest other) {
        if (other == com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetVersionRequest)
    }

    // @@protoc_insertion_point(class_scope:GetVersionRequest)
    private static final com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest();
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetVersionRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetVersionRequest>() {
      @java.lang.Override
      public GetVersionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetVersionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetVersionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetVersionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetVersionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.BaseResponse response = 1;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.BaseResponse response = 1;</code>
     * @return The response.
     */
    com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse getResponse();
    /**
     * <code>.BaseResponse response = 1;</code>
     */
    com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>.Version version = 2;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <code>.Version version = 2;</code>
     * @return The version.
     */
    com.sparrow.switcher.common.grpc.auto.TestProto.Version getVersion();
    /**
     * <code>.Version version = 2;</code>
     */
    com.sparrow.switcher.common.grpc.auto.TestProto.VersionOrBuilder getVersionOrBuilder();
  }
  /**
   * Protobuf type {@code GetVersionResponse}
   */
  public static final class GetVersionResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetVersionResponse)
      GetVersionResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetVersionResponse.newBuilder() to construct.
    private GetVersionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetVersionResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetVersionResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_GetVersionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_GetVersionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse.class, com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse.Builder.class);
    }

    private int bitField0_;
    public static final int RESPONSE_FIELD_NUMBER = 1;
    private com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse response_;
    /**
     * <code>.BaseResponse response = 1;</code>
     * @return Whether the response field is set.
     */
    @java.lang.Override
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.BaseResponse response = 1;</code>
     * @return The response.
     */
    @java.lang.Override
    public com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse getResponse() {
      return response_ == null ? com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.getDefaultInstance() : response_;
    }
    /**
     * <code>.BaseResponse response = 1;</code>
     */
    @java.lang.Override
    public com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponseOrBuilder getResponseOrBuilder() {
      return response_ == null ? com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.getDefaultInstance() : response_;
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private com.sparrow.switcher.common.grpc.auto.TestProto.Version version_;
    /**
     * <code>.Version version = 2;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.Version version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public com.sparrow.switcher.common.grpc.auto.TestProto.Version getVersion() {
      return version_ == null ? com.sparrow.switcher.common.grpc.auto.TestProto.Version.getDefaultInstance() : version_;
    }
    /**
     * <code>.Version version = 2;</code>
     */
    @java.lang.Override
    public com.sparrow.switcher.common.grpc.auto.TestProto.VersionOrBuilder getVersionOrBuilder() {
      return version_ == null ? com.sparrow.switcher.common.grpc.auto.TestProto.Version.getDefaultInstance() : version_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getResponse());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getVersion());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getVersion());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse)) {
        return super.equals(obj);
      }
      com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse other = (com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse) obj;

      if (hasResponse() != other.hasResponse()) return false;
      if (hasResponse()) {
        if (!getResponse()
            .equals(other.getResponse())) return false;
      }
      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (!getVersion()
            .equals(other.getVersion())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetVersionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetVersionResponse)
        com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_GetVersionResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_GetVersionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse.class, com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse.Builder.class);
      }

      // Construct using com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResponseFieldBuilder();
          getVersionFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        response_ = null;
        if (responseBuilder_ != null) {
          responseBuilder_.dispose();
          responseBuilder_ = null;
        }
        version_ = null;
        if (versionBuilder_ != null) {
          versionBuilder_.dispose();
          versionBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.internal_static_GetVersionResponse_descriptor;
      }

      @java.lang.Override
      public com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse getDefaultInstanceForType() {
        return com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse build() {
        com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse buildPartial() {
        com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse result = new com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.response_ = responseBuilder_ == null
              ? response_
              : responseBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.version_ = versionBuilder_ == null
              ? version_
              : versionBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse) {
          return mergeFrom((com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse other) {
        if (other == com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (other.hasVersion()) {
          mergeVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getResponseFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getVersionFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse response_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse, com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.Builder, com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponseOrBuilder> responseBuilder_;
      /**
       * <code>.BaseResponse response = 1;</code>
       * @return Whether the response field is set.
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.BaseResponse response = 1;</code>
       * @return The response.
       */
      public com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>.BaseResponse response = 1;</code>
       */
      public Builder setResponse(com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
        } else {
          responseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.BaseResponse response = 1;</code>
       */
      public Builder setResponse(
          com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.BaseResponse response = 1;</code>
       */
      public Builder mergeResponse(com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse value) {
        if (responseBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            response_ != null &&
            response_ != com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.getDefaultInstance()) {
            getResponseBuilder().mergeFrom(value);
          } else {
            response_ = value;
          }
        } else {
          responseBuilder_.mergeFrom(value);
        }
        if (response_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.BaseResponse response = 1;</code>
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000001);
        response_ = null;
        if (responseBuilder_ != null) {
          responseBuilder_.dispose();
          responseBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.BaseResponse response = 1;</code>
       */
      public com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.Builder getResponseBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.BaseResponse response = 1;</code>
       */
      public com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>.BaseResponse response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse, com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.Builder, com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse, com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponse.Builder, com.sparrow.switcher.common.grpc.auto.TestProto.BaseResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private com.sparrow.switcher.common.grpc.auto.TestProto.Version version_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sparrow.switcher.common.grpc.auto.TestProto.Version, com.sparrow.switcher.common.grpc.auto.TestProto.Version.Builder, com.sparrow.switcher.common.grpc.auto.TestProto.VersionOrBuilder> versionBuilder_;
      /**
       * <code>.Version version = 2;</code>
       * @return Whether the version field is set.
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.Version version = 2;</code>
       * @return The version.
       */
      public com.sparrow.switcher.common.grpc.auto.TestProto.Version getVersion() {
        if (versionBuilder_ == null) {
          return version_ == null ? com.sparrow.switcher.common.grpc.auto.TestProto.Version.getDefaultInstance() : version_;
        } else {
          return versionBuilder_.getMessage();
        }
      }
      /**
       * <code>.Version version = 2;</code>
       */
      public Builder setVersion(com.sparrow.switcher.common.grpc.auto.TestProto.Version value) {
        if (versionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          version_ = value;
        } else {
          versionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.Version version = 2;</code>
       */
      public Builder setVersion(
          com.sparrow.switcher.common.grpc.auto.TestProto.Version.Builder builderForValue) {
        if (versionBuilder_ == null) {
          version_ = builderForValue.build();
        } else {
          versionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.Version version = 2;</code>
       */
      public Builder mergeVersion(com.sparrow.switcher.common.grpc.auto.TestProto.Version value) {
        if (versionBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            version_ != null &&
            version_ != com.sparrow.switcher.common.grpc.auto.TestProto.Version.getDefaultInstance()) {
            getVersionBuilder().mergeFrom(value);
          } else {
            version_ = value;
          }
        } else {
          versionBuilder_.mergeFrom(value);
        }
        if (version_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.Version version = 2;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = null;
        if (versionBuilder_ != null) {
          versionBuilder_.dispose();
          versionBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.Version version = 2;</code>
       */
      public com.sparrow.switcher.common.grpc.auto.TestProto.Version.Builder getVersionBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getVersionFieldBuilder().getBuilder();
      }
      /**
       * <code>.Version version = 2;</code>
       */
      public com.sparrow.switcher.common.grpc.auto.TestProto.VersionOrBuilder getVersionOrBuilder() {
        if (versionBuilder_ != null) {
          return versionBuilder_.getMessageOrBuilder();
        } else {
          return version_ == null ?
              com.sparrow.switcher.common.grpc.auto.TestProto.Version.getDefaultInstance() : version_;
        }
      }
      /**
       * <code>.Version version = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sparrow.switcher.common.grpc.auto.TestProto.Version, com.sparrow.switcher.common.grpc.auto.TestProto.Version.Builder, com.sparrow.switcher.common.grpc.auto.TestProto.VersionOrBuilder> 
          getVersionFieldBuilder() {
        if (versionBuilder_ == null) {
          versionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.sparrow.switcher.common.grpc.auto.TestProto.Version, com.sparrow.switcher.common.grpc.auto.TestProto.Version.Builder, com.sparrow.switcher.common.grpc.auto.TestProto.VersionOrBuilder>(
                  getVersion(),
                  getParentForChildren(),
                  isClean());
          version_ = null;
        }
        return versionBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetVersionResponse)
    }

    // @@protoc_insertion_point(class_scope:GetVersionResponse)
    private static final com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse();
    }

    public static com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetVersionResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetVersionResponse>() {
      @java.lang.Override
      public GetVersionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetVersionResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetVersionResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sparrow.switcher.common.grpc.auto.TestProto.GetVersionResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Version_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Version_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetVersionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetVersionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetVersionResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetVersionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\"-\n\014BaseResponse\022\014\n\004code\030\001 \001" +
      "(\005\022\017\n\007message\030\002 \001(\t\">\n\007Version\022\030\n\020softwa" +
      "re_version\030\001 \001(\t\022\031\n\021last_compile_time\030\002 " +
      "\001(\003\"\023\n\021GetVersionRequest\"P\n\022GetVersionRe" +
      "sponse\022\037\n\010response\030\001 \001(\0132\r.BaseResponse\022" +
      "\031\n\007version\030\002 \001(\0132\010.Version2A\n\010TestGRPC\0225" +
      "\n\nGetVersion\022\022.GetVersionRequest\032\023.GetVe" +
      "rsionResponseB2\n%com.sparrow.switcher.co" +
      "mmon.grpc.autoB\tTestProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseResponse_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_Version_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Version_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Version_descriptor,
        new java.lang.String[] { "SoftwareVersion", "LastCompileTime", });
    internal_static_GetVersionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetVersionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetVersionRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetVersionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetVersionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetVersionResponse_descriptor,
        new java.lang.String[] { "Response", "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
